In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
train_data=pd.read_csv(r"F:\data sets\train.csv")

In [3]:
train_data.head()

ID  Day_No  Course_ID Course_Domain Course_Type  Short_Promotion  \
0   1       1          1   Development      Course                0   
1   2       2          1   Development      Course                0   
2   3       3          1   Development      Course                0   
3   4       4          1   Development      Course                0   
4   5       5          1   Development      Course                0   

   Public_Holiday  Long_Promotion  User_Traffic  Competition_Metric  Sales  
0               1               1         11004               0.007     81  
1               0               1         13650               0.007     79  
2               0               1         11655               0.007     75  
3               0               1         12054               0.007     80  
4               0               1          6804               0.007     41

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 512087 entries, 0 to 512086
Data columns (total 11 columns):
ID                    512087 non-null int64
Day_No                512087 non-null int64
Course_ID             512087 non-null int64
Course_Domain         512087 non-null object
Course_Type           512087 non-null object
Short_Promotion       512087 non-null int64
Public_Holiday        512087 non-null int64
Long_Promotion        512087 non-null int64
User_Traffic          512087 non-null int64
Competition_Metric    510323 non-null float64
Sales                 512087 non-null int64
dtypes: float64(1), int64(8), object(2)
memory usage: 43.0+ MB


In [5]:
train_data.describe()

ID         Day_No      Course_ID  Short_Promotion  \
count  512087.000000  512087.000000  512087.000000    512087.000000   
mean   274007.300650     434.917869     300.388344         0.380244   
std    158228.834029     256.044161     173.365787         0.485447   
min         1.000000       1.000000       1.000000         0.000000   
25%    136962.500000     214.000000     150.000000         0.000000   
50%    273984.000000     427.000000     300.000000         0.000000   
75%    411065.500000     658.000000     451.000000         1.000000   
max    548027.000000     882.000000     600.000000         1.000000   

       Public_Holiday  Long_Promotion   User_Traffic  Competition_Metric  \
count   512087.000000   512087.000000  512087.000000       510323.000000   
mean         0.031639        0.488968   15375.101198            0.073345   
std          0.175038        0.499879    7727.231205            0.100115   
min          0.000000        0.000000     168.000000            0.000000   
25%          0.000000        0.000000   10584.000000            0.010000   
50%          0.000000        0.000000   13776.000000            0.035000   
75%          0.000000        1.000000   18123.000000            0.094000   
max          1.000000        1.000000  100002.000000            0.768000   

               Sales  
count  512087.000000  
mean      120.826924  
std        54.355258  
min         0.000000  
25%        84.000000  
50%       111.000000  
75%       146.000000  
max       682.000000

In [6]:
train_data.dtypes

ID                      int64
Day_No                  int64
Course_ID               int64
Course_Domain          object
Course_Type            object
Short_Promotion         int64
Public_Holiday          int64
Long_Promotion          int64
User_Traffic            int64
Competition_Metric    float64
Sales                   int64
dtype: object

In [8]:
train_data.corr()

ID    Day_No  Course_ID  Short_Promotion  \
ID                  1.000000  0.001052   0.999996        -0.000005   
Day_No              0.001052  1.000000  -0.000506         0.014645   
Course_ID           0.999996 -0.000506   1.000000        -0.000027   
Short_Promotion    -0.000005  0.014645  -0.000027         1.000000   
Public_Holiday      0.001274  0.019112   0.001242        -0.018770   
Long_Promotion     -0.039570 -0.020204  -0.039605        -0.001149   
User_Traffic        0.033604  0.021511   0.033520         0.198785   
Competition_Metric -0.007431  0.003229  -0.007385         0.000182   
Sales               0.017037  0.060012   0.016894         0.367762   

                    Public_Holiday  Long_Promotion  User_Traffic  \
ID                        0.001274       -0.039570      0.033604   
Day_No                    0.019112       -0.020204      0.021511   
Course_ID                 0.001242       -0.039605      0.033520   
Short_Promotion          -0.018770       -0.001149      0.198785   
Public_Holiday            1.000000        0.008319     -0.108305   
Long_Promotion            0.008319        1.000000     -0.204289   
User_Traffic             -0.108305       -0.204289      1.000000   
Competition_Metric       -0.000491       -0.119382     -0.148775   
Sales                    -0.135052       -0.109455      0.829741   

                    Competition_Metric     Sales  
ID                           -0.007431  0.017037  
Day_No                        0.003229  0.060012  
Course_ID                    -0.007385  0.016894  
Short_Promotion               0.000182  0.367762  
Public_Holiday               -0.000491 -0.135052  
Long_Promotion               -0.119382 -0.109455  
User_Traffic                 -0.148775  0.829741  
Competition_Metric            1.000000 -0.022085  
Sales                        -0.022085  1.000000

In [9]:
np.sum(train_data.isnull())

ID                       0
Day_No                   0
Course_ID                0
Course_Domain            0
Course_Type              0
Short_Promotion          0
Public_Holiday           0
Long_Promotion           0
User_Traffic             0
Competition_Metric    1764
Sales                    0
dtype: int64

In [10]:
len(train_data)

512087

In [11]:
train_data.columns

Index(['ID', 'Day_No', 'Course_ID', 'Course_Domain', 'Course_Type',
       'Short_Promotion', 'Public_Holiday', 'Long_Promotion', 'User_Traffic',
       'Competition_Metric', 'Sales'],
      dtype='object')

In [12]:
train_data['Course_Domain'].value_counts()

Development             264295
Software Marketing      166172
Finance & Accounting     77210
Business                  4410
Name: Course_Domain, dtype: int64

In [13]:
train_data['Course_Type'].value_counts()

Course     262747
Program    247576
Degree       1764
Name: Course_Type, dtype: int64

In [14]:
train_data.Competition_Metric.fillna(train_data.Competition_Metric.mean(),axis=0,inplace=True)

In [15]:
np.sum(train_data.isnull())

ID                    0
Day_No                0
Course_ID             0
Course_Domain         0
Course_Type           0
Short_Promotion       0
Public_Holiday        0
Long_Promotion        0
User_Traffic          0
Competition_Metric    0
Sales                 0
dtype: int64

In [20]:
train_data.drop(['Course_Domain'],axis=1,inplace=True)

In [21]:
features=train_data.iloc[:,:-1].values
label=train_data.iloc[:,[-1]].values

In [22]:
print(train_data.shape)
print(features.shape)
print(label.shape)

(512087, 10)
(512087, 9)
(512087, 1)


In [23]:
train_data.head()

ID  Day_No  Course_ID Course_Type  Short_Promotion  Public_Holiday  \
0   1       1          1      Course                0               1   
1   2       2          1      Course                0               0   
2   3       3          1      Course                0               0   
3   4       4          1      Course                0               0   
4   5       5          1      Course                0               0   

   Long_Promotion  User_Traffic  Competition_Metric  Sales  
0               1         11004               0.007     81  
1               1         13650               0.007     79  
2               1         11655               0.007     75  
3               1         12054               0.007     80  
4               1          6804               0.007     41

In [24]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
features[:,3]=encoder.fit_transform(features[:,3])

In [25]:
encoder.classes_

array(['Course', 'Degree', 'Program'], dtype=object)

In [26]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(categorical_features=[3])
features=ohe.fit_transform(features).toarray()

C:\Users\thota\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [27]:
features

array([[1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.0000e+00, 1.1004e+04,
        7.0000e-03],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.0000e+00, 1.3650e+04,
        7.0000e-03],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.0000e+00, 1.1655e+04,
        7.0000e-03],
       ...,
       [0.0000e+00, 0.0000e+00, 1.0000e+00, ..., 1.0000e+00, 1.3671e+04,
        7.0000e-02],
       [0.0000e+00, 0.0000e+00, 1.0000e+00, ..., 1.0000e+00, 8.9040e+03,
        7.0000e-02],
       [0.0000e+00, 0.0000e+00, 1.0000e+00, ..., 1.0000e+00, 1.1445e+04,
        7.0000e-02]])

In [28]:
features.shape

(512087, 11)

In [29]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit_transform(features)

array([[ 0.97415283, -0.05879315, -0.96745863, ...,  1.0223135 ,
        -0.56567551, -0.66383071],
       [ 0.97415283, -0.05879315, -0.96745863, ...,  1.0223135 ,
        -0.22324981, -0.66383071],
       [ 0.97415283, -0.05879315, -0.96745863, ...,  1.0223135 ,
        -0.48142792, -0.66383071],
       ...,
       [-1.02653298, -0.05879315,  1.03363593, ...,  1.0223135 ,
        -0.22053214, -0.03346982],
       [-1.02653298, -0.05879315,  1.03363593, ...,  1.0223135 ,
        -0.83744194, -0.03346982],
       [-1.02653298, -0.05879315,  1.03363593, ...,  1.0223135 ,
        -0.50860456, -0.03346982]])

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(features,label,test_size=0.2,random_state=14)

In [31]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [32]:
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.7965466304579794
0.7959587474258011


In [33]:
predict=model.predict(X_test)
predict

array([[ 91.46243824],
       [146.4494756 ],
       [153.21788777],
       ...,
       [113.43753498],
       [111.13537663],
       [100.1824673 ]])

In [34]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,predict)

596.0618473772477

In [35]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,predict)

18.131197310626128

In [36]:
from sklearn.metrics import r2_score
r2_score(y_test,predict)

0.7959587474258011

# =============================